version: '3.5'

services:
  jwt-template-api-mysql:
    container_name: "jwt-template-api-mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - jwttemplatevolume:/var/lib/mysql
  jwt-template-api:
    depends_on:
      - jwt-template-api-mysql
    container_name: "jwt-template-api"
    image: jwt-template-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: my-secret-pw
      DATABASE_URL: jdbc:mysql://jwt-template-api-mysql:3306/jwttemplate
      ACCESS_TOKEN_EXPIRED: 10
      REFRESH_TOKEN_EXPIRED: 30
volumes:
  jwttemplatevolume: